name: Pull Request CI Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
      - develop

jobs:
  pr_pipeline:
    uses: ./.github/workflows/base-ci.yml
    with:
      sonar_project_key: v1centebarros_mei-tdw-m1
      sonar_organization: v1centebarros-github
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PUBLIC_POCKETBASE_URL: ${{ secrets.PUBLIC_POCKETBASE_URL }}
