name: Production CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  production_pipeline:
    uses: ./.github/workflows/base-ci.yml
    with:
      sonar_project_key: v1centebarros_mei-tdw-m1
      sonar_organization: v1centebarros-github

  deploy_production:
    name: Deploy to production site
    runs-on: ubuntu-latest
    needs: production_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Vercel
        run: npm install --global vercel
      - name: Deploy to production
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
